# =============================================================================
# Adobe Round 1A: PDF Hierarchy Detector Configuration
# =============================================================================

# Project Settings
project_name: "adobe_round1a_pdf_hierarchy"
version: "1.0.0"

# Input/Output Directories
input_folder: "input"
output_folder: "output"
models_folder: "models"
training_data_folder: "training_data"

# =============================================================================
# PROCESSING CONSTRAINTS (Adobe Round 1A Requirements)
# =============================================================================
constraints:
  max_processing_time_seconds: 8     # Reduced from 10 for safety margin
  max_model_size_mb: 200            # Maximum 200MB model size
  max_memory_usage_mb: 1024         # Maximum 1GB RAM usage
  offline_mode: true                # No network calls allowed

# Processing timeout (reduced for performance)
processing_timeout: 8

# =============================================================================
# TITLE DETECTION SETTINGS (Step 1 Requirements)
# =============================================================================
title_detection:
  # Rule-based component (25%)
  font_size_weight: 0.4             # Weight for font size in scoring
  bold_weight: 0.3                  # Weight for bold text in scoring
  position_weight: 0.2              # Weight for position on page
  text_length_weight: 0.1           # Weight for text length (shorter preferred)
  
  # Title detection thresholds
  min_title_font_size: 14           # Minimum font size for title candidates
  max_title_words: 15               # Maximum words in title
  size_tolerance: 0.95              # Consider fonts within 95% of max as candidates
  
  # Subtitle detection (meaningful content below title)
  subtitle_size_ratio: 0.7          # Subtitle must be ≥70% of title font size
  subtitle_max_distance: 50         # Maximum pixel distance below title
  enable_subtitle_detection: true    # Enable subtitle combining with title

# =============================================================================
# HIERARCHY CLASSIFICATION SETTINGS (Step 3 Requirements) - CORRECTED
# =============================================================================
hierarchy:
  # Font size thresholds (relative to document average) - FIXED
  size_ratio_h1: 1.5                # H1 must be ≥150% of average font size
  size_ratio_h2: 1.25               # H2 must be ≥125% of average font size
  size_ratio_h3: 1.1                # H3 must be ≥110% of average font size
  size_ratio_h4: 1.05               # H4 must be ≥105% of average font size
  
  # Text length constraints
  min_heading_length: 3              # Minimum characters for heading
  max_heading_length: 200            # Maximum characters for heading
  title_max_words: 15                # Maximum words in title
  
  # Rule-based patterns (25% of classification logic)
  colon_ending_bonus: 2.0           # Bonus score for text ending with ":"
  bold_heading_bonus: 1.5           # Bonus score for bold text
  numbered_pattern_bonus: 1.3       # Bonus for numbered patterns (1., 1.1, etc.)
  
  # Pattern detection rules
  detect_colon_endings: true         # Detect "Section:" patterns
  detect_numbered_headings: true     # Detect "1.1 Introduction" patterns
  detect_roman_numerals: true        # Detect "I. Introduction" patterns
  
  # Font consistency tracking
  enforce_font_consistency: true     # Same fonts get same hierarchy levels
  consistency_tolerance: 0.1         # Font size tolerance for consistency (±10%)
  
  # ADDITIONAL CORRECTIONS for error handling
  fallback_classification: true      # Enable fallback if ML fails
  min_confidence_threshold: 0.6      # Minimum confidence for ML classification
  max_headings_per_page: 20          # Limit headings per page for performance

# =============================================================================
# FEATURE EXTRACTION SETTINGS
# =============================================================================
features:
  min_heading_size: 12               # Minimum font size for headings
  bold_weight_flag: 16               # PyMuPDF flag bit for bold
  colon_bonus: 1.25                  # Multiplier if line ends with ':'
  size_gap_ratio: 1.15               # Font-size ratio to jump a level
  subtitle_ratio: 0.70               # Subtitle must be ≥ 70% of title size
  number_pattern_bonus: 1.2          # Bonus for numbered patterns

# =============================================================================
# MACHINE LEARNING MODEL SETTINGS (75% of logic) - OPTIMIZED
# =============================================================================
model:
  # Model configuration - CORRECTED for performance
  name: "distilbert-base-uncased"     # DistilBERT for efficiency
  model_size_limit_mb: 95            # Actual model size (~95MB)
  max_length: 256                    # REDUCED from 512 for speed
  
  # Training parameters - OPTIMIZED
  learning_rate: 3e-5
  batch_size: 4                      # REDUCED from 8 for memory efficiency
  num_epochs: 3                      # REDUCED from 5 for faster training
  warmup_ratio: 0.1
  weight_decay: 0.01
  dropout_rate: 0.1
  
  # Feature engineering
  include_font_features: true         # Include font size/weight in features
  include_position_features: true     # Include position information
  include_context_features: false    # DISABLED for speed optimization
  
  # Classification labels
  labels:
    - "title"
    - "h1"
    - "h2"
    - "h3"
    - "h4"
    - "body"
  
  # Model paths
  pretrained_model_path: "models/distilbert_hierarchy_classifier"
  fine_tuned_model_path: "models/fine_tuned_hierarchy_model"
  
  # PERFORMANCE CORRECTIONS
  use_cached_model: true             # Cache model to avoid reloading
  enable_model_quantization: false   # Disable for stability
  torch_compile: false               # Disable for compatibility

# =============================================================================
# TEXT PROCESSING SETTINGS - OPTIMIZED
# =============================================================================
text_processing:
  # Text cleaning
  remove_extra_whitespace: true
  remove_page_numbers: true
  remove_headers_footers: false      # DISABLED for speed
  min_text_length: 3                 # Minimum characters to consider
  
  # Font analysis
  font_size_precision: 1             # Decimal places
