# =============================================================================
# Adobe Round 1A: Improved PDF Hierarchy Detector Configuration
# FOCUS: Quality over Quantity - Much smaller, cleaner JSON outputs
# =============================================================================

# Project Settings
project_name: "adobe_round1a_improved_pdf_hierarchy"
version: "2.0.0"

# Input/Output Directories
input_folder: "input"
output_folder: "output"
models_folder: "models"

# =============================================================================
# QUALITY CONTROL SETTINGS - NEW
# =============================================================================
quality_control:
  max_headings_per_document: 15         # Limit total headings per PDF
  min_confidence_threshold: 0.5         # Minimum confidence for inclusion
  max_text_length: 100                  # Maximum characters per heading
  min_text_length: 3                    # Minimum characters per heading
  similarity_threshold: 0.7             # Remove similar headings (0.0-1.0)
  
# Processing constraints
processing_timeout: 8
max_headings_per_document: 15           # Global limit
min_confidence_threshold: 0.5           # Global confidence threshold

# =============================================================================
# IMPROVED TITLE DETECTION - More Accurate
# =============================================================================
title_detection:
  font_size_weight: 0.5                 # Higher weight for font size
  bold_weight: 0.3                      # Weight for bold text
  position_weight: 0.2                  # Weight for position on page
  
  min_title_font_size: 14               # Minimum font size for title
  max_title_words: 12                   # Reduced max words in title
  size_tolerance: 0.92                  # More strict - 92% of max size
  
  # Title exclusion patterns
  exclude_patterns:
    - "^page \\d+$"                     # Page numbers
    - "^\\d+$"                          # Just numbers
    - "abstract$"                       # Single word abstracts
    - "keywords$"                       # Single word keywords

# =============================================================================
# STRICT HIERARCHY CLASSIFICATION - Quality Focus
# =============================================================================
hierarchy:
  # Font size thresholds - More strict
  size_ratio_h1: 1.4                   # H1 must be ≥140% of average (was 1.5)
  size_ratio_h2: 1.25                  # H2 must be ≥125% of average
  size_ratio_h3: 1.15                  # H3 must be ≥115% of average (was 1.1)
  
  # Text constraints - More restrictive
  min_heading_length: 3                 # Minimum characters
  max_heading_length: 100               # Reduced from 200
  title_max_words: 12                   # Reduced from 15
  max_heading_words: 12                 # New: max words per heading
  
  # Pattern bonuses - Higher thresholds
  colon_ending_bonus: 2.5               # Increased bonus for ":"
  bold_heading_bonus: 2.0               # Increased bonus for bold
  numbered_pattern_bonus: 2.0           # Increased bonus for numbers
  
  # Strict pattern detection
  require_distinctive_formatting: true   # Must have bold OR large font
  min_size_difference: 1.1              # Must be at least 10% larger
  
  # Advanced filtering
  exclude_sentence_endings: true         # Exclude text ending with . ! ?
  exclude_long_sentences: true           # Exclude obvious sentences
  min_confidence_for_inclusion: 0.5      # Minimum confidence to include

# =============================================================================
# FEATURE EXTRACTION - Enhanced Selectivity
# =============================================================================
features:
  # Size thresholds - More conservative
  size_ratio_h1: 1.4                   # Stricter H1 detection
  size_ratio_h2: 1.25                  # Stricter H2 detection  
  size_ratio_h3: 1.15                  # Stricter H3 detection
  
  # Bonus multipliers - Higher for clear indicators
  colon_bonus: 2.0                     # Higher bonus for colon endings
  number_pattern_bonus: 1.8            # Higher bonus for numbered patterns
  bold_bonus: 1.5                     # Bonus for bold text
  
  # New filtering features
  exclude_complete_sentences: true      # Skip obvious sentences
  exclude_common_words_heavy: true      # Skip text with many common words
  require_heading_indicators: false     # Don't require specific patterns
  
  # Content analysis
  max_common_word_ratio: 0.3           # Max ratio of common words (the, and, etc.)
  min_capital_letter_ratio: 0.1        # Min ratio of capital letters

# =============================================================================
# NLP ENHANCEMENT SETTINGS - NEW
# =============================================================================
nlp_processing:
  enable_advanced_filtering: true       # Use NLP for better filtering
  use_spacy_if_available: true         # Use spaCy for linguistic analysis
  pos_tag_filtering: true              # Filter based on part-of-speech tags
  sentence_structure_analysis: true     # Analyze sentence structure
  
  # POS tag preferences for headings
  preferred_starting_pos: ["NOUN", "PROPN", "NUM", "ADJ"]  # Good heading starters
  avoid_starting_pos: ["VERB", "ADP", "DET"]              # Avoid these starters
  max_verbs_in_heading: 1                                 # Max verbs in a heading
  
# =============================================================================
# MACHINE LEARNING MODEL - Optimized for Quality
# =============================================================================
model:
  name: "distilbert-base-uncased"       # Efficient model
  max_length: 128                       # Reduced for faster processing
  
  # Training parameters - Quality focused
  learning_rate: 2e-5                   # Lower learning rate for stability
  batch_size: 8                         # Increased for better gradients
  num_epochs: 5                         # More epochs for better learning
  
  # Model behavior
  use_cached_model: true                # Cache for speed
  confidence_calibration: true          # Calibrate confidence scores
  ensemble_predictions: false           # Single model for speed
  
  # Classification thresholds - More strict
  min_prediction_confidence: 0.6        # Higher threshold
  use_confidence_weighting: true        # Weight by confidence

# =============================================================================
# TEXT PROCESSING - Advanced Filtering
# =============================================================================
text_processing:
  # Advanced cleaning
  remove_extra_whitespace: true
  normalize_unicode: true               # Normalize special characters
  remove_non_printable: true            # Remove non-printable characters
  
  # Content filtering
  min_text_length: 3
  max_text_length: 100                  # Reduced max length
  
  # Pattern-based exclusions
  exclude_patterns:
    - "^\\d+$"                          # Pure numbers
    - "^page \\d+"                      # Page references
    - "www\\.|http"                     # URLs
    - "@.*\\.(com|org|edu)"            # Email addresses
    - "^\\([^)]+\\)$"                  # Parenthetical text
    - "copyright|©|\\d{4}.*rights"      # Copyright notices
    
  # Language-specific filtering
  exclude_common_sentence_starters:
    - "the following"
    - "as shown in"
    - "according to"
    - "it is important"
    - "this section"
    
# =============================================================================
# OUTPUT FORMATTING - Clean JSON Structure
# =============================================================================
output:
  # JSON structure
  include_confidence_scores: false      # Don't include in final JSON
  include_font_info: false             # Don't include font details
  sort_by_page_order: true             # Sort headings by page number
  
  # Quality indicators
  add_quality_metrics: true            # Add processing quality info
  save_processing_summary: true        # Save human-readable summary
  save_intermediate_files: false       # Don't save intermediate data
  
  # File naming
  use_clean_filenames: true            # Remove special characters from filenames
  add_timestamp: false                 # Don't add timestamps to filenames

# =============================================================================
# DEBUGGING AND MONITORING - Optional
# =============================================================================
debug:
  verbose_logging: false               # Detailed logging
  save_rejected_headings: false       # Save headings that were filtered out
  export_confidence_analysis: false   # Export confidence score analysis
  
  # Performance monitoring
  track_processing_time: true         # Track timing for each step
  memory_usage_monitoring: false      # Monitor memory usage
  
# =============================================================================
# BACKWARD COMPATIBILITY - Keep old settings available
# =============================================================================
constraints:
  max_processing_time_seconds: 8
  max_model_size_mb: 200
  offline_mode: true

# Legacy settings (kept for compatibility)
save_intermediate: false              # Don't save intermediate files by default